# Docker-compose pour FileBrowser avec le support de Traefik
# Pour Traefik, pensez a décommenter les lignes networks et labels.

#By PAPAMICA

version: '2'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /DATA:/srv
      - /apps/filebrowser/config.json:/config.json
      - /apps/filebrowser/database.db:/database.db
#    networks:
#      - proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.filebrowser.entrypoints=http"
#      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.papamica.fr`)"
#      - "traefik.http.middlewares.filebrowser-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.filebrowser.middlewares=filebrowser-https-redirect"
#      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
#      - "traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.papamica.fr`)"
#      - "traefik.http.routers.filebrowser-secure.tls=true"
#      - "traefik.http.routers.filebrowser-secure.tls.certresolver=http"
#      - "traefik.docker.network=proxy"
#  
#networks:
#  proxy:
#    external:
#      name: proxy