# Docker-compose pour Website-html avec le support de Traefik
# Pour Traefik, pensez a décommenter les lignes networks et labels.

#By PAPAMICA
version: '2'
services:
  web:
    image: lavoweb/php-5.6
    container_name: website
    volumes:
      - /apps/website/html:/var/www/html
    ports:
      - 80:80
#    networks:
#      - proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.website.entrypoints=http"
#      - "traefik.http.routers.website.rule=Host(`csgo.ndd.fr`)"
#      - "traefik.http.middlewares.website-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.website.middlewares=csgo-https-redirect"
#      - "traefik.http.routers.website-secure.entrypoints=https"
#      - "traefik.http.routers.website-secure.rule=Host(`csgo.ndd.fr`)"
#      - "traefik.http.routers.website-secure.tls=true"
#      - "traefik.http.routers.website-secure.tls.certresolver=http"
#      - "traefik.docker.network=proxy"
#
#networks:
#  proxy:
#    external:
#      name: proxy