# Docker-compose pour Plex avec le support de Traefik
# Pour Traefik, pensez a décommenter les lignes networks et labels.

#By PAPAMICA
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #code claim
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /apps/plex/config:/config
      - /DATA/SERIES:/tv
      - /DATA/FILMS:/movies
    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.plex.entrypoints=http"
#      - "traefik.http.routers.plex.rule=Host(`plex.ndd.fr`)"
#      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.plex.middlewares=plex-https-redirect"
#      - "traefik.http.routers.plex-secure.entrypoints=https"
#      - "traefik.http.routers.plex-secure.rule=Host(`plex.ndd.fr`)"
#      - "traefik.http.routers.plex-secure.tls=true"
#      - "traefik.http.routers.plex-secure.tls.certresolver=http"
#      - "traefik.http.services.plex-secure.loadbalancer.server.port=32400"
#      - "traefik.docker.network=proxy"
#    networks:
#      - proxy
#      
#networks:
#  proxy:
#    external:
#      name: proxy