# Docker-compose pour VSCode avec le support de Traefik
# Pour Traefik, pensez a décommenter les lignes networks et labels.

#By PAPAMICA
version: '2'
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
      - APP_URL=https://wiki.ndd.fr
    volumes:
      - /apps/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
#    networks:
#      - proxy
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.wiki.entrypoints=http"
#      - "traefik.http.routers.wiki.rule=Host(`wiki.ndd.fr`)"
#      - "traefik.http.middlewares.wiki-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.wiki.middlewares=wiki-https-redirect"
#      - "traefik.http.routers.wiki-secure.entrypoints=https"
#      - "traefik.http.routers.wiki-secure.rule=Host(`wiki.ndd.fr`)"
#      - "traefik.http.routers.wiki-secure.tls=true"
#      - "traefik.http.routers.wiki-secure.tls.certresolver=http"
#      - "traefik.docker.network=proxy"
      
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Europe/Paris
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - /apps/bookstack/db:/config
    restart: unless-stopped
#    networks:
#      - proxy
#      
#networks:
#  proxy:
#    external:
#      name: proxy